spring.datasource.url=jdbc:postgresql://localhost:5432/microservice_db?currentSchema=cgschema
spring.datasource.username=postgres
spring.datasource.password=postgres@786

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.mail.username=career.galaxy.corp@gmail.com
spring.mail.password=rxdaauhdwzxhzwpw